def get_czech_text_time_day(key_to_dict: str):
        translation_time_day_dict = {
                    "rel-0.5-hour": "před půl hodinou", 
                    "rel-1-hour": "před hodinou", 
                    "rel-1.5-hours": "před hodinou a půl", 
                    "rel-2-hours": "před dvěma hodinami",
                    "01:00:00": "v jednu hodinu", 
                    "02:00:00": "ve dvě hodiny", 
                    "03:00:00": "ve tři hodiny",
                    "04:00:00": "ve čtyři hodiny", 
                    "05:00:00": "v pět hodin", 
                    "06:00:00": "v šest hodin", 
                    "07:00:00": "v sedm hodin", 
                    "08:00:00": "v osm hodin", 
                    "09:00:00": "v devět hodin",
                    "10:00:00": "v deset hodin", 
                    "11:00:00": "v jedenáct hodin", 
                    "12:00:00": "ve dvanáct hodin", 
                    "13:00:00": "ve třináct hodin",
                    "14:00:00": "ve čtrnáct hodin", 
                    "15:00:00": "v patnáct hodin", 
                    "16:00:00": "v šestnáct hodin", 
                    "17:00:00": "v sedmnáct hodin",
                    "18:00:00": "v osmnáct hodin", 
                    "19:00:00": "v devatenáct hodin", 
                    "20:00:00": "ve dvacet hodin", 
                    "21:00:00": "ve dvacet jedna hodin",
                    "22:00:00": "ve dvacet dva hodin", 
                    "23:00:00": "ve dvacet tři hodin", 
                    "00:00:00": "ve dvacet čtyři hodin",
                    "yesterday": "včera", 
                    "day_before_yesterday": "předevčírem", 
                    "tomorrow":"zítra", 
                    "day_after_tomorrow":"pozítří",
                    "yesterday": "včera",
                    "Monday": "v pondělí", 
                    "Tuesday": "v úterý",
                    "Wednesday": "ve středu", 
                    "Thursday": "ve čtvrtek", 
                    "Friday": "v pátek", 
                    "Saturday": "v sobotu",
                    "Sunday": "v neděli",
                    "last_monday":"minulé pondělí",
                    "last_tuesday":"minulé úterý",
                    "last_wednesday":"minulou středu",
                    "last_thursday":"minulý čtvrtek",
                    "last_friday":"minulý pátek",
                    "last_saturday":"minulou sobotu",
                    "last_sunday":"minulou neděli",
                    "rel_1_hour": "za hodinu", 
                    "rel_2_hours": "za dvě hodiny",
                    "rel_3_hours": "za tři hodiny",
                    "rel_4_hours": "za čtyři hodiny",
                    "rel_5_hours": "za pět hodin",
                    "rel_6_hours": "za šest hodin",
                    "rel_7_hours": "za sedm hodin",
                    "rel_8_hours": "za osm hodin",
                    "rel_9_hours": "za devět hodin",
                    "rel_10_hours": "za deset hodin",
                    "rel_11_hours": "za jedenáct hodin",
                    "rel_12_hours": "za dvanáct hodin",
                    "00:30:00": "v půl jedné ráno", 
                    "01:30:00": "v půl druhé ráno",
                    "02:30:00": "v půl třetí ráno",
                    "03:30:00": "v půl čtvrté ráno",
                    "04:30:00": "v půl páté ráno",
                    "05:30:00": "v půl šesté ráno",                    
                    "06:30:00": "v půl sedmé ráno",
                    "07:30:00": "v půl osmé ráno",
                    "08:30:00": "v osm třicet",
                    "09:30:00": "v devět třicet",
                    "10:30:00": "v deset třicet",
                    "11:30:00": "v jedenáct třicet",
                    "12:30:00": "ve dvanáct třicet",
                    "13:30:00": "ve třináct třicet",
                    "14:30:00": "ve čtrnáct třicet",
                    "15:30:00": "v patnáct třicet",
                    "16:30:00": "v šestnáct třicet",
                    "17:30:00": "v sedmnáct třicet",
                    "18:30:00": "v osmnáct třicet",
                    "19:30:00": "v devatenáct třicet",
                    "20:30:00": "ve dvacet třicet",
                    "21:30:00": "ve dvacet jedna třicet",
                    "22:30:00": "ve dvacet dva třicet",
                    "23:30:00": "ve dvacet tři třicet",
                }
        
        return translation_time_day_dict[key_to_dict]